// App-wide action types
export const ADD_APP_ERROR = 'ADD_APP_ERROR';
export const REMOVE_APP_ERROR = 'REMOVE_APP_ERROR';
export const SET_CURRENT_EDITOR = 'SET_CURRENT_EDITOR';
export const TOGGLE_WELCOME = 'TOGGLE_WELCOME';
export const CHANGE_WELCOME_SEARCH_VALUE = 'CHANGE_WELCOME_SEARCH_VALUE';
export const CHANGE_WELCOME_SEARCH_RESULTS = 'CHANGE_WELCOME_SEARCH_RESULTS';
export const TOGGLE_WELCOME_SEARCH_LOADING = 'TOGGLE_WELCOME_SEARCH_LOADING';

// Clause template action types
export const ADD_CLAUSE_TEMPLATE = 'ADD_CLAUSE_TEMPLATE';
export const REMOVE_CLAUSE_TEMPLATE = 'REMOVE_CLAUSE_TEMPLATE';
export const EDIT_CLAUSE_GRAMMAR = 'EDIT_CLAUSE_GRAMMAR';
export const EDIT_CLAUSE_LOGIC = 'EDIT_CLAUSE_LOGIC';
export const EDIT_CLAUSE_MODEL = 'EDIT_CLAUSE_MODEL';
export const EDIT_CLAUSE_MODEL_SUCCESS = 'EDIT_CLAUSE_MODEL_SUCCESS';
export const EDIT_CLAUSE_PACKAGE_JSON = 'EDIT_CLAUSE_PACKAGE_JSON';
export const EDIT_CLAUSE_SAMPLE = 'EDIT_CLAUSE_SAMPLE';

// Contract-related action types
export const ADD_TO_CONTRACT = 'ADD_TO_CONTRACT';
export const ADD_TO_CONTRACT_SUCCESS = 'ADD_TO_CONTRACT_SUCCESS';
export const DOCUMENT_EDITED = 'DOCUMENT_EDITED';
export const DOCUMENT_EDITED_SUCCESS = 'DOCUMENT_EDITED_SUCCESS';
export const PARSE_CLAUSE_ERROR = 'PARSE_CLAUSE_ERROR';
export const PARSE_CLAUSE_SUCEEDED = 'PARSE_CLAUSE_SUCEEDED';
export const PASTE_TO_CONTRACT = 'PASTE_TO_CONTRACT';
export const PASTE_TO_CONTRACT_SUCCESS = 'PASTE_TO_CONTRACT_SUCCESS';
export const REMOVE_CLAUSE_FROM_CONTRACT = 'REMOVE_CLAUSE_FROM_CONTRACT';

// Model-related action types
export const UPDATE_MODEL_ERROR_SUCCEEDED = 'UPDATE_MODEL_ERROR_SUCCEEDED';
export const UPDATE_MODEL_MANAGER_SUCCEEDED = 'UPDATE_MODEL_MANAGER_SUCCEEDED';
export const VALIDATE_CLAUSE_MODEL_FILES = 'VALIDATE_CLAUSE_MODEL_FILES';

// Templates index action types
export const ADD_NEW_TEMPLATE = 'ADD_NEW_TEMPLATE';
export const ADD_NEW_TEMPLATE_SUCCEEDED = 'ADD_NEW_TEMPLATE_SUCCEEDED';
export const GET_AP_TEMPLATES = 'GET_AP_TEMPLATES';
export const GET_AP_TEMPLATES_SUCEEDED = 'GET_AP_TEMPLATES_SUCEEDED';
export const LOAD_TEMPLATE_OBJECT = 'LOAD_TEMPLATE_OBJECT';
export const LOAD_TEMPLATE_OBJECT_SUCCEEDED = 'LOAD_TEMPLATE_OBJECT_SUCCEEDED';
